# Generated by Django 3.1.1 on 2020-10-15 13:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_id', models.IntegerField()),
                ('way', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=3857)),
                ('feature_data', models.JSONField(verbose_name={})),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('properties', models.JSONField(verbose_name={})),
                ('crop_type', models.IntegerField()),
                ('contour_number', models.IntegerField()),
                ('cropper_ref', models.CharField(default='c_r', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_id', models.CharField(max_length=50, unique=True)),
                ('api_key', models.CharField(default='ApiKey apk.ab435aa666ab42ccc6e4220270e35d9a79ed678fe983b739bd465b5965f61e9c', max_length=300)),
                ('feature_version', models.CharField(default='1', max_length=50)),
                ('feature_message', models.CharField(default='message', max_length=200)),
                ('data', models.JSONField(default=dict)),
                ('area', models.CharField(default='Not Calculated', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=50)),
                ('req_id', models.CharField(max_length=200)),
                ('task_timeout', models.CharField(max_length=100)),
                ('data', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Visual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_id', models.CharField(max_length=200)),
                ('export_id', models.CharField(max_length=200)),
                ('visual_url', models.CharField(max_length=300)),
            ],
        ),
    ]
