# Generated by Django 3.1 on 2020-09-04 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='data',
            field=models.JSONField(default='dict'),
        ),
    ]
