# Generated by Django 3.1 on 2020-09-07 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200904_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='f_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
