# Generated by Django 3.1 on 2020-09-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200907_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='api_key',
            field=models.CharField(default='ApiKey apk.ab435aa666ab42ccc6e4220270e35d9a79ed678fe983b739bd465b5965f61e9c', max_length=300),
        ),
    ]
