# Generated by Django 3.1.1 on 2020-10-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_feature_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='EFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_id', models.CharField(max_length=20)),
                ('farmer_id', models.CharField(max_length=20)),
                ('polygon', models.JSONField(verbose_name={})),
                ('feature_data', models.JSONField(verbose_name={})),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('properties', models.JSONField(verbose_name={})),
                ('crop_type', models.IntegerField()),
                ('contour_number', models.IntegerField()),
            ],
        ),
    ]
